# Copyright 2024, Josh Grady, All rights reserved. 

name: Top Tracks Pipeline Controller

on:
  pull_request:
  push:
    branches:
      - main
   

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  quality:
    needs: setup
    uses: ./.github/workflows/quality.yml

  test:
    needs: setup
    uses: ./.github/workflows/test.yml